#!/usr/bin/env node
// Generated by tools-dynamic — Agent Performance Metrics
import { execSync } from "child_process";
import { readFileSync, readdirSync, existsSync, writeFileSync, statSync, mkdirSync } from "fs";
import { join, basename } from "path";

const ROOT = join(import.meta.dirname, "..", "..");
const AGENTS_DIR = join(ROOT, ".opencode/agents");
const SKILLS_DIR = join(ROOT, ".opencode/skills");
const GITHUB_SKILLS_DIR = join(ROOT, ".github/skills");

function read(path) {
  try { return readFileSync(path, "utf-8"); } catch { return null; }
}

function parseFrontmatter(content) {
  const m = content.match(/^---\n([\s\S]*?)\n(?:---|\.\.\.)\n/);
  if (!m) return null;
  const raw = m[1];
  const fields = {};
  let currentKey = null;
  let currentVal = [];
  let isFolded = false;
  for (const line of raw.split("\n")) {
    if (/^[\w-]+\s*:/.test(line) && !line.startsWith(" ")) {
      if (currentKey) {
        let val = currentVal.join(" ").trim();
        if (isFolded) val = val.replace(/\n\s*/g, " ");
        fields[currentKey] = val;
      }
      const idx = line.indexOf(":");
      currentKey = line.slice(0, idx).trim();
      const rest = line.slice(idx + 1).trim();
      isFolded = rest === ">";
      currentVal = isFolded ? [] : rest ? [rest] : [];
    } else if (currentKey && (line.startsWith("  ") || line.startsWith("\t"))) {
      currentVal.push(line.trim());
    }
  }
  if (currentKey) {
    let val = currentVal.join(" ").trim();
    if (isFolded) val = val.replace(/\n\s*/g, " ");
    fields[currentKey] = val;
  }
  return fields;
}

function countDoNotRules(content) {
  const lines = content.split("\n");
  let inConstraints = false;
  let count = 0;
  for (const line of lines) {
    if (/^##\s+(Constraints|Prohibited)/.test(line)) { inConstraints = true; continue; }
    if (/^##\s+\w/.test(line) && inConstraints) break;
    if (inConstraints && /^\-*\s*(Do\s+NOT|Never|Always)/i.test(line.trim())) count++;
  }
  return count;
}

function countKeywords(fm) {
  if (!fm?.description) return 0;
  const kwSection = fm.description.split("TRIGGER KEYWORDS:")[1] || "";
  return kwSection.split(",").map(k => k.trim()).filter(Boolean).length;
}

function hasSection(content, sectionName) {
  return new RegExp(`^##\\s+${sectionName}`, "m").test(content);
}

function getMode(fm) { return fm?.mode || "unknown"; }

function evaluateAgent(filepath) {
  const name = basename(filepath, ".md");
  const content = read(filepath);
  if (!content) return null;
  const fm = parseFrontmatter(content);
  const kwCount = countKeywords(fm);
  const mode = getMode(fm);
  const isReadOnly = content.includes("edit: deny") && !content.includes("edit: allow");
  const hasModel = fm?.model && fm.model.length > 0;
  const requiredSections = ["Core Responsibilities", "Constraints", "Handoff Protocol"];
  if (name !== "orchestrator") requiredSections.splice(1, 0, "Behavior Rules", "Response Format");
  if (name === "orchestrator") { requiredSections.length = 0; requiredSections.push("Workflow", "Dispatch Rules", "Prohibited"); }
  const sectionsPresent = requiredSections.filter(s => hasSection(content, s));
  const sectionsCompleteness = requiredSections.length > 0 ? sectionsPresent.length / requiredSections.length : 0;
  const doNotCount = countDoNotRules(content);
  const handoffPresent = hasSection(content, "Handoff Protocol");
  let readOnlyConsistent = true;
  if (isReadOnly) readOnlyConsistent = hasModel && content.includes("edit: deny") && content.includes("bash: deny");
  const alerts = [];
  if (kwCount < 10) alerts.push({ severity: "yellow", msg: `Only ${kwCount} keywords (target: ≥ 10)` });
  if (sectionsCompleteness < 1) alerts.push({ severity: "yellow", msg: `Sections: ${sectionsPresent.length}/${requiredSections.length}` });
  if (doNotCount < 5 && name !== "orchestrator") alerts.push({ severity: "yellow", msg: `Only ${doNotCount} Do NOT rules (target: ≥ 5)` });
  if (!handoffPresent && name !== "orchestrator") alerts.push({ severity: "red", msg: "Missing Handoff Protocol section" });
  if (isReadOnly && !hasModel) alerts.push({ severity: "red", msg: "Read-only agent without specialized model" });
  if (isReadOnly && !readOnlyConsistent) alerts.push({ severity: "red", msg: "Read-only inconsistent: missing edit:deny or bash:deny" });
  return { keywords_count: kwCount, mode, sections_completeness: Math.round(sectionsCompleteness * 100), sections_present: sectionsPresent, sections_required: requiredSections, do_not_rules: doNotCount, frontmatter_valid: fm !== null, has_model: hasModel, read_only: isReadOnly, read_only_consistent: readOnlyConsistent, handoff_present: handoffPresent, alerts };
}

function evaluateSkill(dirPath) {
  const name = basename(dirPath);
  const content = read(join(dirPath, "SKILL.md"));
  if (!content) return null;
  const fm = parseFrontmatter(content);
  const kwCount = countKeywords(fm);
  const hasGoal = hasSection(content, "Goal");
  const hasConstraints = hasSection(content, "Constraints");
  const refsDir = join(dirPath, "references");
  const hasRefs = existsSync(refsDir) && readdirSync(refsDir).some(f => f.endsWith(".md"));
  const ghPath = join(GITHUB_SKILLS_DIR, name, "SKILL.md");
  const githubExists = existsSync(ghPath);
  let synced = true;
  if (githubExists) {
    const opencodeRefs = readdirSync(join(SKILLS_DIR, name, "references")).filter(f => f.endsWith(".md"));
    const ghRefsDir = join(GITHUB_SKILLS_DIR, name, "references");
    const ghRefs = existsSync(ghRefsDir) ? readdirSync(ghRefsDir).filter(f => f.endsWith(".md")) : [];
    const missing = opencodeRefs.filter(f => !ghRefs.includes(f));
    if (missing.length > 0) synced = false;
  }
  return { keywords_count: kwCount, has_goal: hasGoal, has_constraints: hasConstraints, has_references: hasRefs, github_exists: githubExists, cross_platform_synced: synced, frontmatter_valid: fm !== null };
}

function runTests() {
  try {
    const testScript = join(import.meta.dirname, "..", "agent-testing", "run.mjs");
    if (!existsSync(testScript)) return null;
    const output = execSync(`node "${testScript}"`, { encoding: "utf-8", cwd: join(import.meta.dirname, "..", "agent-testing") });
    const passMatch = output.match(/PASS:\s+(\d+)/);
    const failMatch = output.match(/FAIL:\s+(\d+)/);
    const totalMatch = output.match(/TOTAL:\s+(\d+)/);
    return { passed: passMatch ? parseInt(passMatch[1]) : 0, failed: failMatch ? parseInt(failMatch[1]) : 0, total: totalMatch ? parseInt(totalMatch[1]) : 0, pass_rate: passMatch && totalMatch ? parseInt(passMatch[1]) / parseInt(totalMatch[1]) : 0, output };
  } catch { return null; }
}

function main() {
  const save = process.argv.includes("--save");
  console.log("╔══════════════════════════════════════════════╗");
  console.log("║   Agent Performance Metrics                  ║");
  console.log("╚══════════════════════════════════════════════╝\n");

  const report = { timestamp: new Date().toISOString(), summary: { agents_evaluated: 0, structural_pass_rate: 0, test_pass_rate: 0, cross_platform_sync_rate: 0, overall_health: "green" }, agents: {}, skills: {}, system: { total_tests: 0, tests_passed: 0, tests_failed: 0, skills_total: 0, skills_synced: 0 }, alerts: [] };

  console.log("── Agents ──");
  const agentFiles = existsSync(AGENTS_DIR) ? readdirSync(AGENTS_DIR).filter(f => f.endsWith(".md")) : [];
  let agentAlerts = 0;
  for (const file of agentFiles) {
    const m = evaluateAgent(join(AGENTS_DIR, file));
    if (!m) continue;
    report.agents[basename(file, ".md")] = m;
    report.summary.agents_evaluated++;
    agentAlerts += m.alerts.length;
    report.alerts.push(...m.alerts.map(a => ({ agent: basename(file, ".md"), ...a })));
    const status = m.alerts.length === 0 ? "🟢" : m.alerts.some(a => a.severity === "red") ? "🔴" : "🟡";
    console.log(`  ${status} ${basename(file, ".md")}: ${m.keywords_count} kw, ${m.sections_completeness}% sections, ${m.do_not_rules} rules`);
  }

  console.log("\n── Skills ──");
  const skillDirs = existsSync(SKILLS_DIR) ? readdirSync(SKILLS_DIR).filter(f => statSync(join(SKILLS_DIR, f)).isDirectory() && f !== "_template" && existsSync(join(SKILLS_DIR, f, "SKILL.md"))) : [];
  let syncedCount = 0;
  for (const dir of skillDirs) {
    const m = evaluateSkill(join(SKILLS_DIR, dir));
    if (!m) continue;
    report.skills[dir] = m;
    report.system.skills_total++;
    if (m.cross_platform_synced) syncedCount++;
    const status = m.cross_platform_synced ? "🟢" : "🔴";
    const gh = m.github_exists ? "✓" : "✗";
    console.log(`  ${status} ${dir}: ${m.keywords_count} kw, sync=${gh}, refs=${m.has_references ? "✓" : "✗"}`);
  }
  report.system.skills_synced = syncedCount;
  report.summary.cross_platform_sync_rate = report.system.skills_total > 0 ? syncedCount / report.system.skills_total : 1;

  console.log("\n── Test Results ──");
  const tests = runTests();
  if (tests) {
    report.system.total_tests = tests.total;
    report.system.tests_passed = tests.passed;
    report.system.tests_failed = tests.failed;
    report.summary.test_pass_rate = tests.pass_rate;
    const status = tests.failed === 0 ? "🟢" : "🔴";
    console.log(`  ${status} ${tests.passed}/${tests.total} passed (${tests.failed} failed)`);
    if (tests.failed > 0) report.alerts.push({ severity: "red", msg: `${tests.failed} test(s) failing` });
  } else { console.log("  ⚪ Tests not available"); }

  const totalStructural = report.summary.agents_evaluated;
  const validStructural = Object.values(report.agents).filter(a => a.frontmatter_valid && a.sections_completeness >= 80).length;
  report.summary.structural_pass_rate = totalStructural > 0 ? validStructural / totalStructural : 0;
  const hasRedAlerts = report.alerts.some(a => a.severity === "red");
  const hasYellowAlerts = report.alerts.some(a => a.severity === "yellow");
  report.summary.overall_health = hasRedAlerts ? "red" : hasYellowAlerts ? "yellow" : "green";

  console.log("\n╔══════════════════════════════════════════════╗");
  console.log("║   Summary                                    ║");
  console.log("╚══════════════════════════════════════════════╝");
  console.log(`  Overall Health:     ${report.summary.overall_health === "green" ? "🟢" : report.summary.overall_health === "yellow" ? "🟡" : "🔴"} ${report.summary.overall_health}`);
  console.log(`  Agents evaluated:   ${report.summary.agents_evaluated}`);
  console.log(`  Structural pass:    ${Math.round(report.summary.structural_pass_rate * 100)}%`);
  console.log(`  Test pass rate:     ${Math.round(report.summary.test_pass_rate * 100)}%`);
  console.log(`  Cross-platform:     ${Math.round(report.summary.cross_platform_sync_rate * 100)}%`);
  console.log(`  Alerts:             ${report.alerts.filter(a => a.severity === "red").length} 🔴 ${report.alerts.filter(a => a.severity === "yellow").length} 🟡`);

  if (report.alerts.length > 0) {
    console.log("\n── Alerts ──");
    for (const a of report.alerts) console.log(`  ${a.severity === "red" ? "🔴" : "🟡"} [${a.agent || "system"}] ${a.msg}`);
  }
  if (save) {
    mkdirSync(join(import.meta.dirname, "reports"), { recursive: true });
    writeFileSync(join(import.meta.dirname, "reports", "latest.json"), JSON.stringify(report, null, 2));
    writeFileSync(join(import.meta.dirname, "reports", `report-${Date.now()}.json`), JSON.stringify(report, null, 2));
    console.log(`\n  Report saved to tools/agent-metrics/reports/`);
  }
  console.log("");
  return report;
}

main();
