import { existsSync } from 'fs';
import { WorkflowGenerator } from './workflow-generator.mjs';

const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RED = '\x1b[31m';
const CYAN = '\x1b[36m';
const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';

export class Reporter {
  toJSON(results, projectPath) {
    const summary = this._buildSummary(results);
    return JSON.stringify({
      timestamp: new Date().toISOString(),
      projectPath,
      platforms: results,
      summary,
    }, null, 2);
  }

  toHTML(results, projectPath) {
    const summary = this._buildSummary(results);
    const platformRows = results.map(p => {
      const health = this._healthColor(p);
      const agentRows = p.agents.map(a =>
        `<tr><td>${a.name}</td><td>${a.role}</td><td>${a.mode}</td><td>${a.keywords.length}</td><td>${a.hasHandoff ? '✓' : '✗'}</td></tr>`
      ).join('');
      const skillRows = p.skills.map(s =>
        `<tr><td>${s.name}</td><td>${s.keywords.length}</td><td>${s.references.length}</td></tr>`
      ).join('');
      const workflowRows = p.workflows.map(w =>
        `<tr><td>${w.name}</td><td>${w.steps}</td><td>${w.agents.join(', ')}</td></tr>`
      ).join('');

      return `
        <div class="platform">
          <h2>${p.platform} <span class="health-${health}">${health.toUpperCase()}</span></h2>
          <p>Version: ${p.platformVersion} | Agents: ${p.agents.length} | Skills: ${p.skills.length}</p>
          ${agentRows ? `<h3>Agents</h3><table><tr><th>Name</th><th>Role</th><th>Mode</th><th>Keywords</th><th>Handoff</th></tr>${agentRows}</table>` : ''}
          ${skillRows ? `<h3>Skills</h3><table><tr><th>Name</th><th>Keywords</th><th>References</th></tr>${skillRows}</table>` : ''}
          ${workflowRows ? `<h3>Workflows</h3><table><tr><th>Name</th><th>Steps</th><th>Agents</th></tr>${workflowRows}</table>` : ''}
          <h3>Capabilities</h3><pre>${JSON.stringify(p.nativeCapabilities, null, 2)}</pre>
        </div>`;
    }).join('');

    return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>tools_dynamic Report</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 960px; margin: 2rem auto; padding: 0 1rem; }
  h1 { border-bottom: 2px solid #333; }
  .platform { border: 1px solid #ccc; border-radius: 8px; padding: 1rem; margin: 1rem 0; }
  .health-green { color: #16a34a; } .health-yellow { color: #ca8a04; } .health-red { color: #dc2626; }
  table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; }
  th, td { border: 1px solid #ddd; padding: 0.4rem; text-align: left; }
  th { background: #f5f5f5; }
  pre { background: #f8f8f8; padding: 0.5rem; border-radius: 4px; overflow-x: auto; }
  .summary { display: flex; gap: 1rem; flex-wrap: wrap; }
  .summary-card { border: 1px solid #ccc; border-radius: 8px; padding: 0.8rem 1.2rem; text-align: center; flex: 1; min-width: 100px; }
  .summary-card .number { font-size: 2rem; font-weight: bold; }
</style></head>
<body>
  <h1>🔍 tools_dynamic Report</h1>
  <p>Project: ${projectPath}</p>
  <p>Timestamp: ${new Date().toISOString()}</p>
  <div class="summary">
    <div class="summary-card"><div class="number">${summary.totalPlatforms}</div>Platforms</div>
    <div class="summary-card"><div class="number">${summary.totalAgents}</div>Agents</div>
    <div class="summary-card"><div class="number">${summary.totalSkills}</div>Skills</div>
    <div class="summary-card"><div class="number">${summary.totalWorkflows}</div>Workflows</div>
  </div>
  ${platformRows}
  <p style="color:#666;font-size:0.8rem;margin-top:2rem">Generated by tools_dynamic v2.0.0-alpha</p>
</body></html>`;
  }

  printAnalysis(results, projectPath) {
    console.log(`\n  ${BOLD}🔍 Analysis: ${projectPath}${RESET}\n`);

    if (results.length === 0) {
      console.log(`  ${YELLOW}No agent platforms detected.${RESET}`);
      console.log(`  ℹ️  Run ${CYAN}tools-dynamic list-platforms${RESET} to see detectable platforms.\n`);
      return;
    }

    for (const platform of results) {
      const health = this._healthIcon(platform);
      console.log(`  ${health} ${BOLD}${platform.platform}${RESET} ${platform.platformVersion}`);
      console.log(`     Config: ${platform.configPaths.join(', ')}`);
      console.log(`     Agents: ${platform.agents.length}  |  Skills: ${platform.skills.length}  |  Workflows: ${platform.workflows.length}`);
      console.log(`     Tools: ${platform.existingTools.length > 0 ? platform.existingTools.join(', ') : '(none)'}`);

      const caps = platform.nativeCapabilities;
      const enabled = Object.entries(caps).filter(([, v]) => v).map(([k]) => k);
      if (enabled.length > 0) console.log(`     Capabilities: ${enabled.join(', ')}`);

      if (platform.agents.length > 0) {
        console.log(`\n     ${BOLD}Agents:${RESET}`);
        for (const agent of platform.agents) {
          const handoffIcon = agent.hasHandoff ? '📋' : '  ';
          console.log(`       ${handoffIcon} ${agent.name} (${agent.mode}) — ${agent.role}`);
          if (agent.keywords.length > 0) {
            console.log(`          Keywords: ${agent.keywords.slice(0, 8).join(', ')}${agent.keywords.length > 8 ? '...' : ''}`);
          }
        }
      }

      if (platform.skills.length > 0) {
        console.log(`\n     ${BOLD}Skills:${RESET}`);
        for (const skill of platform.skills) {
          console.log(`       📦 ${skill.name} (${skill.keywords.length} keywords)`);
        }
      }

      if (platform.workflows.length > 0) {
        console.log(`\n     ${BOLD}Workflows:${RESET}`);
        for (const wf of platform.workflows) {
          console.log(`       ⚡ ${wf.name} — ${wf.steps} steps [${wf.agents.join(', ')}]`);
        }
      }

      console.log();
    }

    this._printSummary(results);
  }

  printDiagnosis(results, projectPath) {
    const issues = this.diagnose(results);
    console.log(`\n  ${BOLD}🔬 Diagnosis: ${projectPath}${RESET}\n`);

    if (issues.length === 0) {
      console.log(`  ${GREEN}No issues found. Configuration looks good!${RESET}\n`);
      return;
    }

    const blockers = issues.filter(i => i.severity === 'blocker');
    const warnings = issues.filter(i => i.severity === 'warning');
    const infos = issues.filter(i => i.severity === 'info');

    if (blockers.length > 0) {
      console.log(`  ${BOLD}🔴 Blockers (${blockers.length}):${RESET}`);
      for (const issue of blockers) {
        console.log(`    • ${issue.message}`);
        if (issue.suggestion) console.log(`      → ${CYAN}${issue.suggestion}${RESET}`);
      }
      console.log();
    }

    if (warnings.length > 0) {
      console.log(`  ${BOLD}🟡 Warnings (${warnings.length}):${RESET}`);
      for (const issue of warnings) {
        console.log(`    • ${issue.message}`);
        if (issue.suggestion) console.log(`      → ${CYAN}${issue.suggestion}${RESET}`);
      }
      console.log();
    }

    if (infos.length > 0) {
      console.log(`  ${BOLD}ℹ️  Info (${infos.length}):${RESET}`);
      for (const issue of infos) {
        console.log(`    • ${issue.message}`);
        if (issue.suggestion) console.log(`      → ${CYAN}${issue.suggestion}${RESET}`);
      }
      console.log();
    }

    if (blockers.length === 0 && warnings.length === 0 && infos.length > 0) {
      console.log(`  ${GREEN}No blockers or warnings — ${infos.length} suggestion(s)${RESET}\n`);
    }
  }

  diagnose(results) {
    const issues = [];

    for (const platform of results) {
      for (const agent of platform.agents) {
        if (agent.keywords.length < 10) {
          issues.push({
            platform: platform.platform,
            agent: agent.name,
            severity: 'warning',
            message: `"${agent.name}" has only ${agent.keywords.length} TRIGGER KEYWORDS (target: ≥ 10)`,
            suggestion: 'Add more trigger keywords to the frontmatter',
          });
        }

        if (!agent.hasHandoff) {
          issues.push({
            platform: platform.platform,
            agent: agent.name,
            severity: 'info',
            message: `"${agent.name}" lacks a Handoff Protocol section`,
            suggestion: 'Add ## Handoff Protocol to the agent definition',
          });
        }

        if (agent.sections.length < 3) {
          issues.push({
            platform: platform.platform,
            agent: agent.name,
            severity: 'warning',
            message: `"${agent.name}" has only ${agent.sections.length} sections (target: ≥ 3)`,
            suggestion: 'Add more sections (Core Responsibilities, Constraints, etc.)',
          });
        }
      }

      for (const skill of platform.skills) {
        if (skill.keywords.length < 10) {
          issues.push({
            platform: platform.platform,
            skill: skill.name,
            severity: 'info',
            message: `Skill "${skill.name}" has only ${skill.keywords.length} keywords`,
            suggestion: 'Expand TRIGGER KEYWORDS in the skill frontmatter',
          });
        }
      }

      if (platform.workflows.length === 0 && platform.agents.length >= 2) {
          const wfg = new WorkflowGenerator();
        const suggested = wfg.suggestWorkflows(platform);
        if (suggested.length > 0) {
          issues.push({
            platform: platform.platform,
            severity: 'info',
            message: `No workflows defined — ${suggested.length} workflow(s) could be auto-generated`,
            suggestion: `Consider adding: ${suggested.map(w => w.name).join(', ')}`,
          });
        }
      }
    }

    return issues;
  }

  printPlatforms() {
    const platforms = [
      { name: 'OpenCode', indicators: '.opencode/, AGENTS.md, opencode.json', agents: '.opencode/agents/*.md', skills: '.opencode/skills/*/SKILL.md' },
      { name: 'VS Code / Copilot', indicators: '.github/copilot-instructions.md', agents: '.github/agents/*.md', skills: '.github/skills/*/SKILL.md' },
      { name: 'Claude Code', indicators: 'CLAUDE.md, .claude/', agents: '.claude/agents/*.md', skills: '.claude/skills/*/SKILL.md', extra: '.claude/settings.json, rules/, mcp.json' },
      { name: 'Antigravity', indicators: 'antigravity.yaml, antigravity.json', agents: 'defined in config', skills: 'defined in config' },
    ];

    console.log(`\n  ${BOLD}Detectable Platforms${RESET}\n`);
    for (const p of platforms) {
      console.log(`  ${BOLD}${p.name}${RESET}`);
      console.log(`     Indicators: ${p.indicators}`);
      console.log(`     Agents:     ${p.agents}`);
      console.log(`     Skills:     ${p.skills}`);
      if (p.extra) console.log(`     Extra:      ${p.extra}`);
      console.log();
    }
  }

  _buildSummary(results) {
    return {
      totalPlatforms: results.length,
      totalAgents: results.reduce((a, p) => a + p.agents.length, 0),
      totalSkills: results.reduce((a, p) => a + p.skills.length, 0),
      totalWorkflows: results.reduce((a, p) => a + p.workflows.length, 0),
      overallHealth: results.every(p => this._healthColor(p) === 'green') ? 'green'
        : results.some(p => this._healthColor(p) === 'red') ? 'red' : 'yellow',
    };
  }

  _healthColor(platform) {
    if (platform.agents.length === 0) return 'yellow';
    const allHaveHandoff = platform.agents.every(a => a.hasHandoff);
    const allHaveKeywords = platform.agents.every(a => a.keywords.length >= 10);
    return allHaveHandoff && allHaveKeywords ? 'green' : allHaveHandoff || allHaveKeywords ? 'yellow' : 'red';
  }

  _healthIcon(platform) {
    const color = this._healthColor(platform);
    return color === 'green' ? '🟢' : color === 'yellow' ? '🟡' : '🔴';
  }

  _printSummary(results) {
    const summary = this._buildSummary(results);
    const icon = summary.overallHealth === 'green' ? '🟢' : summary.overallHealth === 'yellow' ? '🟡' : '🔴';
    console.log(`  ${BOLD}── Summary ──${RESET}`);
    console.log(`  ${icon}  ${summary.totalPlatforms} platform(s), ${summary.totalAgents} agent(s), ${summary.totalSkills} skill(s), ${summary.totalWorkflows} workflow(s)`);
    console.log();
  }
}
