#!/usr/bin/env node
// Generated by tools-dynamic — Context Manager: Token Estimation & Compaction
import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync, statSync } from "fs";
import { join, basename, extname } from "path";

const ROOT = join(import.meta.dirname, "..", "..");
const AGENTS_DIR = join(ROOT, "{{agentsDir}}");
const SKILLS_DIR = join(ROOT, "{{skillsDir}}");

function read(path) {
  try { return readFileSync(path, "utf-8"); } catch { return null; }
}

function estimateTokens(text) {
  if (!text) return 0;
  return Math.ceil(text.length / 4);
}

function estimateTokensFromFiles(dir, ext = ".md") {
  if (!existsSync(dir)) return 0;
  let total = 0;
  const entries = readdirSync(dir, { withFileTypes: true, recursive: true });
  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith(ext)) {
      const content = read(join(entry.parentPath, entry.name));
      if (content) total += estimateTokens(content);
    }
  }
  return total;
}

const MODEL_LIMITS = {
  "gpt-4": 8192, "gpt-4-turbo": 128000, "gpt-4o": 128000, "gpt-4o-mini": 128000,
  "claude-3-opus": 200000, "claude-3-sonnet": 200000, "claude-3-haiku": 200000,
  "claude-3.5-sonnet": 200000, "claude-4-opus": 200000,
  "deepseek-v3": 131072, "deepseek-r1": 131072, "deepseek-v4": 131072,
  "gemini-1.5-pro": 1048576, "gemini-1.5-flash": 1048576, "gemini-2.0-flash": 1048576,
  "llama-3": 8192, "llama-3.1": 131072, "mistral-large": 131072,
  "codestral": 256000, "qwen-2.5": 131072,
};

function detectModel() {
  const hugo = join(ROOT, ".opencode", "opencode.json");
  if (existsSync(hugo)) {
    try {
      const cfg = JSON.parse(readFileSync(hugo, "utf-8"));
      const model = cfg.agents?.[0]?.model || cfg.model || "";
      if (model && MODEL_LIMITS[model]) return model;
    } catch {}
  }
  return "gpt-4o";
}

function printHeader() {
  console.log("╔══════════════════════════════════════════════╗");
  console.log("║   Context Manager — Token Estimation         ║");
  console.log("╚══════════════════════════════════════════════╝\n");
}

function scanAll() {
  const agentsTokens = estimateTokensFromFiles(AGENTS_DIR);
  const skillsTokens = estimateTokensFromFiles(SKILLS_DIR);
  const totalAgents = existsSync(AGENTS_DIR) ? readdirSync(AGENTS_DIR).filter(f => f.endsWith(".md")).length : 0;
  const skillDirs = existsSync(SKILLS_DIR) ? readdirSync(SKILLS_DIR).filter(f => f !== "_template" && statSync(join(SKILLS_DIR, f)).isDirectory()) : [];
  const totalSkills = skillDirs.length;
  return { agents: { fileCount: totalAgents, totalTokens: agentsTokens, avgTokens: totalAgents > 0 ? Math.round(agentsTokens / totalAgents) : 0 }, skills: { dirCount: totalSkills, totalTokens: skillsTokens, avgTokens: totalSkills > 0 ? Math.round(skillsTokens / totalSkills) : 0 }, totalTokens: agentsTokens + skillsTokens };
}

function checkThresholds(ctxTokens, modelLimit, threshold = 0.8, criticalThreshold = 0.95) {
  const pct = ctxTokens / modelLimit;
  const alerts = [];
  if (pct >= criticalThreshold) alerts.push({ severity: "red", msg: `Context at ${(pct * 100).toFixed(1)}% — CRITICAL, immediate compaction required` });
  else if (pct >= threshold) alerts.push({ severity: "yellow", msg: `Context at ${(pct * 100).toFixed(1)}% — approaching limit, consider compaction` });
  else alerts.push({ severity: "green", msg: `Context at ${(pct * 100).toFixed(1)}% — within safe range` });
  return { percentage: pct, usedTokens: ctxTokens, limitTokens: modelLimit, remaining: modelLimit - ctxTokens, threshold, criticalThreshold, alerts };
}

function main() {
  const args = process.argv.slice(2);
  const modelName = args.includes("--model") ? args[args.indexOf("--model") + 1] : detectModel();
  const modelLimit = MODEL_LIMITS[modelName] || 128000;
  const save = args.includes("--save");
  const checkOnly = args.includes("--check");
  const jsonOutput = args.includes("--json");

  if (checkOnly) {
    const data = scanAll();
    const result = checkThresholds(data.totalTokens, modelLimit);
    if (jsonOutput) {
      console.log(JSON.stringify({ model: modelName, ...result, files: data }, null, 2));
    } else {
      printHeader();
      console.log(`  Model:       ${modelName} (limit: ${modelLimit.toLocaleString()} tokens)`);
      console.log(`  Used:        ${result.usedTokens.toLocaleString()} tokens`);
      console.log(`  Remaining:   ${result.remaining.toLocaleString()} tokens`);
      console.log(`  Usage:       ${(result.percentage * 100).toFixed(1)}%\n`);
      console.log(`  Status:      ${result.alerts[0].severity === "red" ? "🔴" : result.alerts[0].severity === "yellow" ? "🟡" : "🟢"} ${result.alerts[0].msg}`);
      console.log(`  Agents:      ${data.agents.fileCount} files, ${data.agents.totalTokens.toLocaleString()} tokens (avg ${data.agents.avgTokens}/file)`);
      console.log(`  Skills:      ${data.skills.dirCount} dirs, ${data.skills.totalTokens.toLocaleString()} tokens (avg ${data.skills.avgTokens}/dir)\n`);
    }
    process.exit(result.percentage >= 0.95 ? 1 : 0);
  }

  printHeader();
  const data = scanAll();
  console.log("── Scan Results ──\n");
  console.log(`  Agents:      ${data.agents.fileCount} files, ${data.agents.totalTokens.toLocaleString()} tokens (avg ${data.agents.avgTokens}/file)`);
  console.log(`  Skills:      ${data.skills.dirCount} dirs, ${data.skills.totalTokens.toLocaleString()} tokens (avg ${data.skills.avgTokens}/dir)`);
  console.log(`  Total:       ${data.totalTokens.toLocaleString()} tokens\n`);

  const result = checkThresholds(data.totalTokens, modelLimit);
  console.log("── Context Budget ──\n");
  console.log(`  Model:       ${modelName}`);
  console.log(`  Limit:       ${modelLimit.toLocaleString()} tokens`);
  console.log(`  Used:        ${result.usedTokens.toLocaleString()} tokens`);
  console.log(`  Remaining:   ${result.remaining.toLocaleString()} tokens`);
  console.log(`  Usage:       ${(result.percentage * 100).toFixed(1)}%`);
  console.log(`  Threshold:   ${(result.threshold * 100)}%  (yellow)`);
  console.log(`  Critical:    ${(result.criticalThreshold * 100)}%  (red)`);
  console.log(`  Status:      ${result.alerts[0].severity === "red" ? "🔴" : result.alerts[0].severity === "yellow" ? "🟡" : "🟢"} ${result.alerts[0].msg}\n`);

  if (result.percentage >= result.threshold) {
    console.log("── Compaction Recommendations ──\n");
    console.log("  To compact conversation context, consider:");
    console.log("  1. Summarize early conversation turns into a condensed preamble");
    console.log("  2. Prune completed tool outputs that are no longer relevant");
    console.log("  3. Consolidate agent responses into key decisions only");
    console.log("  4. Remove resolved issues and completed action items");
    console.log("  5. Use the context-steward agent for automatic compaction\n");
  }

  if (save) {
    const report = { timestamp: new Date().toISOString(), model: modelName, modelLimit, usedTokens: result.usedTokens, remaining: result.remaining, percentage: result.percentage, threshold: result.threshold, criticalThreshold: result.criticalThreshold, status: result.alerts[0].severity, files: data };
    mkdirSync(join(import.meta.dirname, "reports"), { recursive: true });
    writeFileSync(join(import.meta.dirname, "reports", "context-latest.json"), JSON.stringify(report, null, 2));
    writeFileSync(join(import.meta.dirname, "reports", `context-${Date.now()}.json`), JSON.stringify(report, null, 2));
    console.log(`  Report saved to tools/context-manager/reports/\n`);
  }
}

main();
