#!/usr/bin/env node
// Generated by tools-dynamic — Agent & Skill Testing Framework
import { readFileSync, readdirSync, existsSync, statSync } from "fs";
import { join, relative, basename } from "path";

const ROOT = join(import.meta.dirname, "..", "..");
const AGENTS_DIR = join(ROOT, ".opencode/agents");
const SKILLS_DIR = join(ROOT, ".opencode/skills");
const GITHUB_SKILLS_DIR = join(ROOT, ".github/skills");

let passed = 0, failed = 0, skipped = 0;
const results = [];

function ok(agent, test, msg) { passed++; results.push({ agent, test, status: "PASS", msg }); }
function fail(agent, test, msg) { failed++; results.push({ agent, test, status: "FAIL", msg }); }
function skip(agent, test, msg) { skipped++; results.push({ agent, test, status: "SKIP", msg }); }

function read(path) {
  try { return readFileSync(path, "utf-8"); } catch { return null; }
}

function parseFrontmatter(content) {
  const m = content.match(/^---\n([\s\S]*?)\n(?:---|\.\.\.)\n/);
  if (!m) return null;
  const raw = m[1];
  const fields = {};
  let currentKey = null;
  let currentVal = [];
  let isFolded = false;
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (/^[\w-]+\s*:/.test(line) && !line.startsWith(" ")) {
      if (currentKey) {
        let val = currentVal.join(" ").trim();
        if (isFolded) val = val.replace(/\n\s*/g, " ");
        fields[currentKey] = val;
      }
      const idx = line.indexOf(":");
      currentKey = line.slice(0, idx).trim();
      const rest = line.slice(idx + 1).trim();
      isFolded = rest === ">";
      currentVal = isFolded ? [] : rest ? [rest] : [];
    } else if (currentKey && (line.startsWith("  ") || line.startsWith("\t"))) {
      currentVal.push(trimmed);
    }
  }
  if (currentKey) {
    let val = currentVal.join(" ").trim();
    if (isFolded) val = val.replace(/\n\s*/g, " ");
    fields[currentKey] = val;
  }
  return fields;
}

function checkFrontmatterFields(file, fm, required, displayName) {
  const name = displayName || basename(file, ".md");
  for (const [field, rules] of Object.entries(required)) {
    if (!fm || fm[field] === undefined) {
      fail(name, `frontmatter.${field}`, `Missing required field: ${field}`);
      continue;
    }
    if (rules.startsWithMatch && !fm[field].startsWith(rules.startsWithMatch)) {
      fail(name, `frontmatter.${field}`, `Should start with "${rules.startsWithMatch}", got "${fm[field].slice(0, 50)}..."`);
      continue;
    }
    if (rules.includes && !fm[field].toLowerCase().includes(rules.includes.toLowerCase())) {
      fail(name, `frontmatter.${field}`, `Should include "${rules.includes}"`);
      continue;
    }
    ok(name, `frontmatter.${field}`, `${field} is valid`);
  }
}

function checkSections(file, content, required) {
  const name = basename(file, ".md");
  for (const [section, pattern] of Object.entries(required)) {
    const re = new RegExp(pattern, "m");
    if (re.test(content)) {
      ok(name, `section.${section}`, `Section "${section}" found`);
    } else {
      if (content.includes(pattern)) {
        ok(name, `section.${section}`, `Section "${section}" found`);
      } else {
        fail(name, `section.${section}`, `Section "${section}" not found`);
      }
    }
  }
}

function checkKeywords(file, fm) {
  const name = basename(file, ".md");
  if (!fm || !fm.description) { skip(name, "keywords", "No description to check"); return []; }
  if (!fm.description.startsWith("TRIGGER KEYWORDS:")) {
    fail(name, "keywords", "description must start with TRIGGER KEYWORDS:");
    return [];
  }
  const kwSection = fm.description.split("TRIGGER KEYWORDS:")[1]?.split(".")?.[0] || fm.description.split("TRIGGER KEYWORDS:")[1] || "";
  const keywords = kwSection.split(",").map(k => k.trim()).filter(Boolean);
  if (keywords.length < 5) {
    fail(name, "keywords", `Only ${keywords.length} keywords, expected at least 5`);
  } else {
    ok(name, "keywords", `${keywords.length} keywords found`);
  }
  return keywords;
}

function testAgent(filepath) {
  const name = basename(filepath, ".md");
  const content = read(filepath);
  if (!content) { fail(name, "file", "Cannot read file"); return; }
  if (!content.startsWith("---")) { fail(name, "file", "Must start with YAML frontmatter"); return; }
  const fm = parseFrontmatter(content);
  if (!fm) { fail(name, "frontmatter", "Cannot parse frontmatter"); return; }
  ok(name, "frontmatter.parse", "Frontmatter parsed");

  const isOrchestrator = name === "orchestrator";
  checkFrontmatterFields(filepath, fm, {
    description: { startsWithMatch: "TRIGGER KEYWORDS:" },
    mode: { includes: isOrchestrator ? "primary" : "subagent" },
    permission: { includes: "edit" },
  });

  const isReadOnly = content.includes("edit: deny");
  if (isReadOnly) {
    checkFrontmatterFields(filepath, fm, { model: { includes: "claude" } });
  }

  checkKeywords(filepath, fm);

  const sections = isOrchestrator
    ? { "Workflow": "## Workflow", "Dispatch Rules": "## Dispatch Rules", "Prohibited": "## Prohibited" }
    : { "Core Responsibilities": "## Core Responsibilities", "Constraints": "## Constraints", "Handoff Protocol": "## Handoff Protocol" };
  if (!isReadOnly && !isOrchestrator) sections["Behavior Rules"] = "## Behavior Rules";
  checkSections(filepath, content, sections);
}

function testSkill(filepath) {
  const name = basename(join(filepath, ".."));
  const content = read(filepath);
  if (!content) { fail(name, "file", "Cannot read file"); return; }
  if (!content.startsWith("---")) { fail(name, "file", "Must start with YAML frontmatter"); return; }
  const fm = parseFrontmatter(content);
  if (!fm) { fail(name, "frontmatter", "Cannot parse frontmatter"); return; }
  ok(name, "frontmatter.parse", "Frontmatter parsed");
  checkFrontmatterFields(filepath, fm, {
    description: { startsWithMatch: "TRIGGER KEYWORDS:" },
    name: { includes: name },
  }, name);
  checkKeywords(filepath, fm);
  checkSections(filepath, content, { Goal: "## Goal", Constraints: "## Constraints" });

  const skillDir = join(filepath, "..");
  const refsDir = join(skillDir, "references");
  if (existsSync(refsDir) && readdirSync(refsDir).some(f => f.endsWith(".md"))) {
    ok(name, "references.dir", "references/ directory has .md files");
  } else {
    fail(name, "references.dir", "references/ directory missing or empty");
  }
}

function testCrossPlatformSync() {
  if (!existsSync(SKILLS_DIR)) { skip("system", "cross-platform", "Skills directory not found"); return; }
  if (!existsSync(GITHUB_SKILLS_DIR)) { skip("system", "cross-platform", "GitHub skills directory not found"); return; }
  const opencodeSkills = readdirSync(SKILLS_DIR).filter(f => f !== "_template");
  for (const skill of opencodeSkills) {
    const ghPath = join(GITHUB_SKILLS_DIR, skill, "references");
    if (!existsSync(ghPath)) { skip(skill, "cross-platform", `${GITHUB_SKILLS_DIR}/${skill} not found`); continue; }
    const opencodeFiles = readdirSync(join(SKILLS_DIR, skill, "references")).filter(f => f.endsWith(".md"));
    const githubFiles = readdirSync(ghPath).filter(f => f.endsWith(".md"));
    const missingInGithub = opencodeFiles.filter(f => !githubFiles.includes(f));
    const extraInGithub = githubFiles.filter(f => !opencodeFiles.includes(f));
    if (missingInGithub.length === 0 && extraInGithub.length === 0) {
      ok(skill, "cross-platform", `references/ synced between skills dirs`);
    } else {
      const issues = [];
      if (missingInGithub.length) issues.push(`missing: ${missingInGithub.join(", ")}`);
      if (extraInGithub.length) issues.push(`extra: ${extraInGithub.join(", ")}`);
      fail(skill, "cross-platform", issues.join("; "));
    }
  }
}

console.log("╔══════════════════════════════════════════════╗");
console.log("║   Agent & Skill Testing Framework            ║");
console.log("╚══════════════════════════════════════════════╝\n");

console.log("── Agents ──");
const agentFiles = existsSync(AGENTS_DIR) ? readdirSync(AGENTS_DIR).filter(f => f.endsWith(".md")) : [];
for (const file of agentFiles) { testAgent(join(AGENTS_DIR, file)); }

console.log("\n── Skills ──");
const skillFiles = existsSync(SKILLS_DIR)
  ? readdirSync(SKILLS_DIR).filter(f => statSync(join(SKILLS_DIR, f)).isDirectory() && f !== "_template").flatMap(d => {
      const skPath = join(SKILLS_DIR, d, "SKILL.md");
      return existsSync(skPath) ? [skPath] : [];
    })
  : [];
for (const file of skillFiles) { testSkill(file); }

console.log("\n── Cross-Platform Sync ──");
testCrossPlatformSync();

console.log("\n╔══════════════════════════════════════════════╗");
console.log("║   Summary                                    ║");
console.log("╚══════════════════════════════════════════════╝");
console.log(`  PASS:  ${passed}`);
console.log(`  FAIL:  ${failed}`);
console.log(`  SKIP:  ${skipped}`);
console.log(`  TOTAL: ${passed + failed + skipped}\n`);

if (failed > 0) {
  console.log("── Failed Tests ──");
  for (const r of results.filter(r => r.status === "FAIL")) {
    console.log(`  [${r.agent}] ${r.test}: ${r.msg}`);
  }
  console.log("");
}

export { results, passed, failed, skipped };
